# Generated by Django 5.2.13 on 2026-06-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_chat_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='likeandcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
